In [2]:
import pandas as pd

# Replace 'your_file.csv' with the actual path to your CSV file
df = pd.read_csv('data/users-score-2023.csv')

# Display the first 10 rows
df.head(10)

   user_id Username  anime_id                  Anime Title  rating
0        1    Xinil        21                    One Piece       9
1        1    Xinil        48                  .hack//Sign       7
2        1    Xinil       320                       A Kite       5
3        1    Xinil        49             Aa! Megami-sama!       8
4        1    Xinil       304       Aa! Megami-sama! Movie       8
5        1    Xinil       306  Abenobashi Mahou☆Shoutengai       8
6        1    Xinil        53                Ai Yori Aoshi       7
7        1    Xinil        47                        Akira       5
8        1    Xinil       591               Amaenaide yo!!       6
9        1    Xinil        54            Appleseed (Movie)       7

In [3]:
# Export the first 10 rows to a new CSV file
df.head(10).to_csv('final_users-score10_rows.csv', index=False)

In [4]:
print(df.dtypes)

user_id         int64
Username       object
anime_id        int64
Anime Title    object
rating          int64
dtype: object

In [5]:
from supabase import create_client, Client

url = "https://yvspjnxnwdanqwymcwtw.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2c3Bqbnhud2RhbnF3eW1jd3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzIwMTIsImV4cCI6MjA2MTA0ODAxMn0.iVIH5OwBDXHM9yJGnQhxn7zkuFEmmQsZwGIKJiu3MRo"
supabase: Client = create_client(url, key)

In [12]:
# Now inserting will work
for record in df.to_dict(orient="records")[11:]:
    # supabase.table("final_animedataset").upsert(record, on_conflict=["anime_id"]).execute()
    supabase.table("eda-score-2023").insert(record).execute()
    print("done")

done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done

APIError: {'code': '23505', 'details': 'Key (anime_id)=(49) already exists.', 'hint': None, 'message': 'duplicate key value violates unique constraint "eda-score-2023_pkey"'}